// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqrfgzgsfzcyqszgbjyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxcmZnemdzZnpjeXFzemdianlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NDU3ODksImV4cCI6MjA3MDMyMTc4OX0.CyIdGRNF0vwFKE2Bmlt4lNtfEh-wDUdYxzwnHiEOZZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});